Features/add line validation vars
ics-creative/160609_animation-image-generator pull request #47
Opened 2022-03-10 09:26 UTC by ics-matsumoto

#28 の対応を行いました。

■ 変更概要
- バリデーションの種類をEnumで定義しました。↓の選択肢と対応します
![image](https://user-images.githubusercontent.com/59550270/157629678-8079f74f-980e-4b13-82f1-d2590cabb01d.png)

- 種類ごとにバリデーション関数を定義しました
- バリデートエラー時のメッセージバリエーションが増えたため、日英ともにメッセージを追加しました

■ このPRに含んでいないもの
- バリデーションの種類を指定するUIは未作成です
  - 現時点では`LineValidationType.ANIMATION_STAMP`をハードコードしています
  - 「TODO: バリデーションの種類をUIで指定できるようにする」と記載されている2箇所を変更して別の種別を指定すればバリデータを変更できます

■ 特に確認いただきたい箇所
- 各種別のバリデータの設定（上限サイズや再生時間等）が[制作ガイドライン](https://creator.line.me/ja/guideline/sticker/)とそもそも合っているか確認いただきたいです
  - → product/common-src/validators/lineImageValidators.ts
- 各バリデータの実装も誤りがないかチェックいただけるとありがたいです 
  - → product/common-src/validators/validationFunctions/validate*.ts
- メッセージに改善案がありましたらコメントをください（日英とも）
  - 画像サイズはそもそもの要件がややこしいため、制作ガイドラインの記述からあまりずれすぎない範囲で簡潔に説明するのが難しいです...

<img width="250" alt="image" src="https://user-images.githubusercontent.com/59550270/157631678-c428f718-f3ff-4b8d-b251-a7dc7f2257a3.png">

2022-03-14 03:06 UTC, ics-nohara commented on product/common-src/i18n/fillString.ts
> +};
@ics-matsumoto 
ちょっと面倒ですが、数値で定義してしまうと、文の差し替え時に混乱しがちになってしまうので、ほかに懸念がなければ文字列で指定をしたいです。

```
const fillString = (template: string, values: Map<string, (string|number)>) => {
  let result = template;
  for (let key of values.keys()) {
    const placeHolder = '${' + (key) + '}';
    if (!result.includes(placeHolder)) {
      // ${key}がない
      console.warn(
        `Placeholder ${placeHolder} is not found in template: ${template}.`
      );
    }
    result = result.replace(placeHolder, String(values.get(key)));
  });
  if (result.match(/\$\{[0-9a-zA-Z\\_]+\}/)) {
    // 結果に${key}がまだ残っている
    console.warn(`Not enough params to fill template. result: ${result}`);
  }
  return result;
};

console.log(fillString("文字列${key1}, ${key2}, ${key3}",  
  new Map<string, (string|number)>(
     [
       ["key1", 500], 
       ["key2", "value2"], 
       // warningお試し
       // ["key3", "value3"], 
       ["key4", "value3"], // warningお試し
       ["_key_5", "value3"]// warningお試し
    ]))
);
```

2022-03-14 03:10 UTC, ics-nohara requested changes
気になる点をコメントしました

2022-03-14 03:19 UTC, ics-matsumoto commented on product/common-src/i18n/fillString.ts
> +};
@ics-nohara 了解です。${1}みたいな数字にしていたのは既存のテンプレート文字列と合わせるためだけなので、変えて良いのであれば下記のような形式にするのが良いかと思いました：

```ts
fillString(
  "${imgType}は横${width}×縦${height}px以内で作成してください", 
  {imgType: "メイン画像", width: 500, height: 400}
);
```

特にMapにする必要もないかと思いましたがいかがでしょうか？

2022-03-14 05:01 UTC, ics-nohara commented on product/common-src/i18n/fillString.ts
> +};
@ics-matsumoto Mapでなくても問題ないと思いますー！

2022-03-14 05:40 UTC, ics-nohara commented
制作ガイドラインと照らし合わせ確認しました。問題なさそうですが、できたらテストを追加してさらに安心したいです。

2022-03-14 06:40 UTC, ics-matsumoto commented on product/common-src/i18n/fillString.ts
> +};
@ics-nohara やってみたのですが、どっちにしてもテンプレートの編集が危なっかしくて混乱を極めたので、関数として定義するように改めました。

```ts
// 定義
VALIDATE_amount: ({ min, max, current }) =>
    `イラストは最低${min}~最大${max}枚で設定ください(現在は${current}枚です)。`,
// 利用
const message = VALIDATE_amount({ min, max, current: count });
```

2022-03-14 07:10 UTC, ics-nishihara commented on product/common-src/type/ImageValidator.ts
> +/** バリデータのバリデーションエラーの型 */
@ics-matsumoto 
細かいですが、ここは「バリデーション結果の型」なのかなと思いました。`ValidationResult`型には、問題ないケースの結果も含まれているので…。

2022-03-14 07:10 UTC, ics-nishihara commented on product/common-src/validators/validationFunctions/validateImageSizeExactAndMin.ts
> +  return isValidMax && (isValidExactW || isValidExactH)
@ics-matsumoto 
確認ですが
> 横/縦のどちらかが480px
この条件はどちらも480pxは許容していますでしょうか？
もしNGの場合、480px × 480pxの場合バリデーションを抜けてしまう気がします。

2022-03-14 07:16 UTC, ics-matsumoto commented on product/common-src/validators/validationFunctions/validateImageSizeExactAndMin.ts
> +  return isValidMax && (isValidExactW || isValidExactH)
@ics-nishihara 
オリジナルのガイドラインが下記の記載なので、480*480はValid（許容）かな、と思います
```
- 横480px × 縦480px以内
- 横/縦のどちらかが480px
- 横が480pxの場合は、縦が320px以上
- 縦が480pxの場合は、横が200px以上
```

2022-03-14 07:20 UTC, ics-matsumoto commented on product/common-src/type/ImageValidator.ts
> +/** バリデータのバリデーションエラーの型 */
@ics-nishihara ですね。修正しておきました🙏

2022-03-14 08:15 UTC, ics-nishihara approved these changes

2022-03-14 08:15 UTC, ics-nishihara commented on product/common-src/type/ImageValidator.ts
> +/** バリデータのバリデーションエラーの型 */
ありがとうございます

2022-03-15 01:54 UTC, ics-nohara approved these changes
テストに関しては別PRということでこちらはマージします

2022-03-15 01:54 UTC, merged

2022-03-15 01:57 UTC, ics-nohara commented on product/common-src/i18n/fillString.ts
> +};
理想的でとてもいいと思います！