チェックルールのセレクター追加
ics-creative/160609_animation-image-generator pull request #51
Opened 2022-03-16 11:05 UTC by ics-nishihara

チェックルールのセレクターをUIに追加しました。
チェックルールの配列、ラベル名の配列を使って、for文で生成しています。

暫定的にconsole出力するイベントハンドラーを追加しています。

記法等問題ないかなども合わせてご確認いただけると幸いです。

よろしくお願いします。

![スクリーンショット 2022-03-16 19 08 28](https://user-images.githubusercontent.com/48976682/158576285-d493099e-2a1c-4f6d-9c8c-845d3932da12.png)

2022-03-16 11:51 UTC, ics-matsumoto commented on product/common-src/checkRule/checkRule.ts
> +export const checkRuleList = [
@ics-nishihara PRありがとうございます！
このあたりの定義なのですが、
https://github.com/ics-creative/160609_animation-image-generator/blob/310d9e89a5ed87a10a88900e79649d86099cecdf/product/common-src/type/LineValidationType.ts
と重複している感があるので、できれば一つにしたいです。

2022-03-16 11:51 UTC, ics-matsumoto commented on product/common-src/checkRule/checkRule.ts
> +export const checkRuleLabel = {
@ics-nishihara メッセージは日英出し分けがあるので`src/app/i18n/locale-(ja|en).ts`に定義したいです。
（別途でも大丈夫です！）

2022-03-16 11:51 UTC, ics-matsumoto commented on product/src/app/components/app/app.scss
> +    margin: 24px 0 8px;
@ics-nishihara 私も詳しくないのですが、どうやらこの辺りのスタイルは、他の部分ではBootstrapのクラスを使っているように見えます。できれば他の部分と揃えておきたいのですが、可能でしょうか？

2022-03-18 06:31 UTC, ics-nishihara commented on product/common-src/checkRule/checkRule.ts
> +export const checkRuleList = [
ありがとうございます。
型定義を`LineValidationType`に合わせました。

2022-03-18 06:31 UTC, ics-nishihara commented on product/common-src/checkRule/checkRule.ts
> +export const checkRuleLabel = {
@ics-matsumoto 
こちら国際化対応を行いました。

2022-03-18 06:47 UTC, ics-nishihara commented on product/src/app/components/app/app.scss
> +    margin: 24px 0 8px;
こちら、既存のCSSに合わせる形に修正しました。

2022-03-18 07:06 UTC, ics-matsumoto commented on product/common-src/i18n/localeDataEn.ts
> +  RULE_emoji: 'Animation Emoji'
@ics-nishihara 多言語対応の追加ありがとうございます😀
ユーザーに見せるスタンプ等の種別名称は下記の公式の名前をベースにしたいです。お手数ですが調整いただけますでしょうか？
https://creator.line.me/en/guideline/sticker/

2022-03-18 07:10 UTC, ics-matsumoto commented on product/common-src/checkRule/checkRule.ts
> +export const checkRuleLabel = {
@ics-nishihara ありがとうございます！（別途英訳の中身についてコメントしました🙏）

2022-03-18 07:14 UTC, ics-matsumoto commented on product/src/app/components/app/app.html
> +      </select>
@ics-nishihara すみません💦前回コメントできていなかったのですが、チェックルールはLINEスタンプのみの機能なので、用途をLineにした時だけ表示された方が良いかな、と思います。こちら調整可能でしょうか？

<img width="293" alt="image" src="https://user-images.githubusercontent.com/59550270/158954034-fcaeb0cb-6509-4b47-b0f7-7dfadc9eb43b.png">

2022-03-18 10:18 UTC, ics-nishihara commented on product/src/app/components/app/app.html
> +      </select>
@ics-matsumoto 
すみません完全に考慮を漏れていました。

条件を追加してLINEのみ表示するように修正しました。

2022-03-22 09:34 UTC, ics-nishihara commented on product/common-src/i18n/localeDataEn.ts
> +  RULE_emoji: 'Animation Emoji'
@ics-matsumoto 
ありがとうございます。

名称を公式に合わせました。

2022-03-25 11:03 UTC, ics-nohara requested changes
気になるところをコメントしました

2022-03-25 11:03 UTC, ics-nohara commented on product/common-src/i18n/localeDataJa.ts
> +  RULE_effect: '  エフェクトスタンプ画像',
```suggestion
  RULE_effect: 'エフェクトスタンプ画像',
```
余分な空白が入ってしまっているようなので、特に意図がなければ取っておきたいですー

2022-03-25 11:06 UTC, ics-matsumoto commented on product/src/app/components/app/app.html
> +        <p class="mb-2">チェックルール</p>
@ics-nishihara 後出しですみません！できればこのラベルも英語に対応したいのですがお願いできますでしょうか？

2022-03-25 12:03 UTC, ics-nishihara commented on product/src/app/components/app/app.html
> +        <p class="mb-2">チェックルール</p>
@ics-matsumoto 
こちらも国際化対応しました。

2022-03-25 12:04 UTC, ics-nishihara commented on product/common-src/i18n/localeDataJa.ts
> +  RULE_effect: '  エフェクトスタンプ画像',
@ics-nohara 
不要な空白だったの削除しました。

2022-03-25 12:59 UTC, ics-matsumoto approved these changes

2022-03-28 01:15 UTC, ics-nohara approved these changes

2022-03-28 01:29 UTC, ics-nohara commented on product/common-src/i18n/localeDataEn.ts
> +  CHECK_RULE: 'チェックルール',
@ics-nishihara すみません、一度Approveしたのですが、こちらの内容を英語にしておきたいです。
また、変数名をほかの箇所と統一させて`大文字(カテゴリー)_小文字`としておきたいです。
```suggestion
  RULE_title: 'Check rule,
```

2022-03-28 01:30 UTC, ics-nohara requested changes
気になるところを見つけたのでコメントしました。

2022-03-28 03:23 UTC, ics-nishihara commented on product/common-src/i18n/localeDataEn.ts
> +  CHECK_RULE: 'チェックルール',
@ics-nohara 
ありがとうございます。
変数名・英語表記を修正しました。

2022-03-28 03:26 UTC, ics-nohara approved these changes

2022-03-28 03:27 UTC, merged