アプリアイコンを更新＆更新処理をスクリプトにする
ics-creative/160609_animation-image-generator pull request #76
Opened 2023-01-26 02:38 UTC by ics-matsumoto

@ics-nohara @ics-nishihara 

#74 でアイコン画像が更新されたので、新しい画像からアプリのアイコンファイルを作成しました。
合わせて、更新作業を（ある程度）自動化しています。
手順も併せて記載していますのでご確認をお願いします。

2023-01-26 11:46 UTC, ics-nohara approved these changes
ご対応ありがとうございます。スクリプトも正しく動作することを確認しました。

2023-01-26 12:13 UTC, ics-nohara commented
アイコン作成を自動化のついでに、PSDからのPNGファイルの出力自体もアセット生成機能を使って書き出したら、出力場所も意識せずに作業できて楽かなと思ったのですが、そうした場合の懸念はありますか？

2023-01-27 10:12 UTC, ics-matsumoto commented
> アイコン作成を自動化のついでに、PSDからのPNGファイルの出力自体もアセット生成機能を使って書き出したら、出力場所も意識せずに作業できて楽かなと思ったのですが、そうした場合の懸念はありますか？

どこまでいい感じにできるのかあまりわかっていないのですが、懸念などは特にないです！

2023-01-27 10:23 UTC, ics-nishihara approved these changes
問題ないと思いますのでApproveします。

PSDのアセット書き出しについては、PSDがある階層以下にしか書き出しできなかった気がするので、`resources`フォルダに移す必要があると思います。

2023-01-30 05:14 UTC, ics-matsumoto commented
@ics-nohara @ics-nishihara 

アイコンのPSDを`product/resources/app-icon`に移動した上で、アセット生成でPNGを出力するように修正しました。
他にやっておいた方が良さそうなことなどありましたらコメントください。

残った`preloader.fla`（ローディングサークルの画像）も、（ひとつだけルートに置いておくのも微妙なので）合わせて`resources`に移動しています。
※ ここだけflaになってるのもややこしいので、今後調整することがあればCSSにしてしまった方が良い気もします

2023-01-30 05:28 UTC, ics-nohara requested changes
@ics-matsumoto 誤字だけ修正お願いします～！

2023-01-30 05:28 UTC, ics-nohara commented on product/resources/app-icon/README.md
> +   1. `app-icon-assets`の画像が更新されてことを確認してください
```suggestion
   1. `app-icon-assets`の画像が更新されたことを確認してください
```

2023-01-30 06:40 UTC, ics-nohara approved these changes

2023-01-30 06:41 UTC, ics-nohara commented
@ics-matsumoto approvesしました。私からは他ありません～！

2023-02-01 04:15 UTC, merged